AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proverbial
Globals:
  Function:
    Timeout: 5
Resources:
  ProverbialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://jboursiquot-proverbial/a71e0dded659ef25339a90b2f0023b49
      Handler: proverbial
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /proverb
            Method: GET
  CheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://jboursiquot-proverbial/e72946c4a7a4a85396d705a0465d6b86
      Handler: checker
      Runtime: go1.x
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Checks
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /check
            Method: GET
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Checks
  PickerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://jboursiquot-proverbial/509a0c4b02051eab04322ecb505214f7
      Handler: picker
      Runtime: go1.x
      Tracing: Active
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Checks
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Checks
  Checks:
    Type: AWS::Serverless::SimpleTable
Outputs:
  ProverbialAPI:
    Description: Get yourself a proverb
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proverb/
  ProverbialFunction:
    Description: Proverbs Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ProverbialFunction
      - Arn
  ChechkerAPI:
    Description: Check an endpoint for its ability to serve proverbs
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/check
  CheckerFunction:
    Description: Checker Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CheckerFunction
      - Arn
  PickerFunction:
    Description: Picker Lambda Function ARN
    Value:
      Fn::GetAtt:
      - PickerFunction
      - Arn
  ProverbialFunctionIamRole:
    Description: Implicit IAM Role created for Proverbial function
    Value:
      Fn::GetAtt:
      - ProverbialFunctionRole
      - Arn
