AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proverbial
Globals:
  Function:
    Timeout: 5
Resources:
  ProverbialFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://jboursiquot-proverbial/a8d00f509979463b698e35bb6ddc3037
      Handler: proverbial
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /proverb
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
Outputs:
  ProverbialAPI:
    Description: Get yourself a proverb
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/proverb/
  ProverbialFunction:
    Description: Proverbs Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ProverbialFunction
      - Arn
  ProverbialFunctionIamRole:
    Description: Implicit IAM Role created for Proverbial function
    Value:
      Fn::GetAtt:
      - ProverbialFunctionRole
      - Arn
